using Fusion;
using Mono.Cecil;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEditor;
using UnityEngine;
using UnityEngine.SceneManagement;

public class FusionInGameManager : MonoBehaviour
{
    private static FusionInGameManager instance;

    // ë„¤íŠ¸ì›Œí¬ ì£¼ì²´
    [SerializeField] private NetworkRunner runner;
    // ì½œë°±
    [SerializeField] private FusionInGameCallBack callback;
    // ìƒì„±í•  ë„¤íŠ¸ì›Œí¬ í”„ë¦¬íŒ¹
    [SerializeField] private NetworkObject playerPrefab;

    [Header("===Player===")]
    private Dictionary<PlayerRef, NetworkObject> _spawnedCharacters = new Dictionary<PlayerRef, NetworkObject>();
    [SerializeField] Transform[] spawnedPoint;
    [SerializeField] LayerMask[] playerLayerList;

    public NetworkObject NetworkPlayerPrefab { get => playerPrefab; }

    public static FusionInGameManager GetInstance()
    {
        if (instance == null)
        {
            Debug.LogError("FusionManager ì¸ìŠ¤í„´ìŠ¤ê°€ ì¡´ì¬í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤.");
            return null;
        }
        return instance;
    }

    private void Awake()
    {
        if (!instance)
        {
            instance = this;
        }

        // ë„¤íŠ¸ì›Œí¬ì™€ í†µì‹ í•˜ê¸° ìœ„í•´ì„œ 
        if (!gameObject.TryGetComponent<FusionInGameCallBack>(out callback))
            callback = gameObject.AddComponent<FusionInGameCallBack>();

        // NetworkRunner ì„¸íŒ…
        runner = FusionSettingRunner.GetInstance().GetRunner();

        // ì½œë°± ì¬ë“±ë¡
        runner.AddCallbacks(callback);

        _spawnedCharacters = new Dictionary<PlayerRef, NetworkObject>();
    }

    private void Start()
    {
        // ë¦¬ì†ŒìŠ¤ í´ë”ì—ì„œ ê°€ì ¸ì˜¤ê¸° 
        //GameObject var = Resources.Load<GameObject>("PlayerPrefab");
        // playerPrefab = var.GetComponent<NetworkObject>();

        // ëª…ì‹œì ìœ¼ë¡œ ë“±ë¡ 
        SceneRef currentSceneRef = SceneRef.FromIndex(SceneManager.GetActiveScene().buildIndex);

        if (runner == null) 
        {
            Debug.Log("ì—¬ê¸°ì„œëŠ” NULL ì¼ ìˆ˜ê°€ ì—†ìŒ");
            return;
        }
        Debug.Log(currentSceneRef);
        NetworkObject[] networkObjects = new NetworkObject[1] { playerPrefab };
        runner.RegisterSceneObjects(currentSceneRef, networkObjects);

    }

    private void Update()
    {
        if (Input.GetKeyDown(KeyCode.L))
            InstancePlayer(); 
    }

    public void InstancePlayer() 
    {
        if (runner == null) 
        {
            Debug.Log("Runnerê°€ NULLì…ë‹ˆë‹¤. í”Œë ˆì´ì–´ë¥¼ ìƒì„±í•  ìˆ˜ ì—†ìŠµë‹ˆë‹¤.");
        }

        // ì„œë²„(í˜¸ìŠ¤íŠ¸)ë§Œ ì˜¤ë¸Œì íŠ¸ ìƒì„± ê°€ëŠ¥ 
        if (runner.IsServer) 
        {
            Debug.Log("playerPrefab isValid: " + playerPrefab.IsValid);

            Debug.Log("í˜„ì¬ ì„¸ì…˜ì— ë“¤ì–´ì˜¨ ì¸ì› " + runner.ActivePlayers.Count());
            
            int index = 0;
            foreach (PlayerRef pl in runner.ActivePlayers) 
            {

                try
                {
                    NetworkObject netPlayerObj = runner.Spawn(playerPrefab, spawnedPoint[0].position, Quaternion.identity);
                    netPlayerObj.gameObject.layer = playerLayerList[index];

                    // ë”•ì…”ë„ˆë¦¬ì— ë„£ê¸°
                    _spawnedCharacters.Add(pl, netPlayerObj);

                    index++;
                }
                catch (Exception e)
                {
                    Debug.LogError($"ğŸ”¥ Spawn ì˜ˆì™¸ (PlayerRef {pl}): {e}");
                }
            }
        }
    }

}
